### ISSUE TITLE
Bei newGeneration werden keine neuen Species erstellt

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#19]
Benötigt weitere Untersuchung, aber die Tatsache, dass immer die gleiche Anzahl an Species existiert ist für mich etwas fragwürdig. Hier kann es sein, dass noch Fehler vorliegen.

Zu kontrollierende Methoden:
- newGeneration (in Pool)
- matchGenomes (in Species)
- weitere mit diesen verknüpften Methoden

**Comment by Keydara** [comment]
Es scheint sich so zu verhalten, dass die maximale Population auf die vorhandenen Spezies aufgeteilt wird, wobei sich die "stärkere" Spezies durchsetzt.
Soll heißen: In mehreren Tests verhält sich die Anwendung so, dass es 2 Spezies gibt mit bspw. 87 und 13 Genomes. Nach Aufruf von newGeneration() wird die erste Spezies 99 und die 2. Spezies 1 Genome beinhalten.
Alle folgenden Aufrufe von newGeneration() ändern dies nicht mehr.

Eine Spezies enthält, nach genug Generationen (<10), immer Population-1 Genome und die andere (sofern vorhanden) 1 Genom.

**Comment by MPreloaded** [comment]
Gerade getestet: Bei der aktuellen Implementierung scheinen alle Genomes einer Species nach einem gewissen Zeitraum genau die gleiche Anzahl an Neuronen und Verbindungen aufzuweisen. Dies ist besonders komisch, da keine neuen Generationen mit anderen Anzahlen auftreten.

**Comment by Keydara** [comment]
Ist mir auch aufgefallen. Das wäre nur halb so schlimm, wenn in neuen Generationen auch mal neue Spezies auftreten würden.
Sehr merkwürdig.

**Comment by MPreloaded** [comment]
Hängt wahrscheinlich alles zusammen... wenn ich jetzt vernünftig testen könnte... :D

**Comment by MPreloaded** [comment]
Weiterer Fehler:

Wenn eine neue Generation erstellt wird, bewegen sich nicht nur alle Genomes im selben Bereich, dieser Bereich ist auch noch unrealistisch. Auf einen Schlag werden aus 3 Genes 12. Das ist nicht realistisch und benötigt weitere Nachforschungen.

**Comment by MPreloaded** [comment]
Fehler behoben. Alle Genomes einer Species teilten irgendwann die selbe Liste von Genes...

MPreloaded@499c8b351b10e0a0c2f972ea12ef464af281b759
