### ISSUE TITLE
Auswahl Species

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#21]
Meiner Meinung nach sollte bei der Auswahl der Species die Möglichkeit bestehen, einmal allgemeine Daten zu sehen (so wie es jetzt aussieht) und dann aber auch die Möglichkeit eines der aktuell besten Netzwerke (erst nur "textlich" mit den Verbindungs- und Neuroneninformationen, später grafisch) zu sehen. So kann auch beim durchgehen der verschiedenen Species (vielleicht) erkannt werden, worin die evolutionären Unterschiede bestehen.

**Comment by Keydara** [comment]
Da bin ich absolut deiner Meinung. Hatte generell vor, eine grafische/detailliertere Darstellung der einzelnen Netzwerke zu implementieren..

**Comment by Keydara** [comment]
ca5d47a2c8940f63304facc5bfdce3f8fb43cf98
Noch nicht optimal/final, aber man kann schon damit arbeiten...
Bitte beachten: Verbindungen(Genes) welche disabled sind, werden ausgeblendet

**Comment by MPreloaded** [comment]
Ich denke das hier kann geschlossen werden
