### ISSUE TITLE
Error durch neuesten Commit

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#28]
`X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  20
  Current serial number in output stream:  21`

**Comment by Keydara** [comment]
Wo tritt der Fehler auf? Ich bekomme den nicht...

**Comment by MPreloaded** [comment]
Ich hatte den gerade beim Starten der MainApp... scheint aber wohl ein xserver-Fehler zu sein...

**Comment by Keydara** [comment]
Wenn der bei CreateNewContext rausfliegt, weiss ich auch nicht so wirklich, was ich da ändern kann. Vielleicht kommt xserver nicht mit dem Canvas klar?

**Comment by MPreloaded** [comment]
Weiß ich nicht... ich hatte grade ein Update aber ich schau mal, ob eine alte version noch funktioniert

**Comment by Keydara** [comment]
https://bbs.archlinux.org/viewtopic.php?id=195435
Hilft dir das vllt weiter?

**Comment by MPreloaded** [comment]
Ja, ich hab jetzt ne Ahnung, was falsch läuft

**Comment by MPreloaded** [comment]
Ok funzt....
Kurze Frage:
Was sind die blauen Neuronen (falls Hidden, warum haben die keine Verbindung zu dem Output)?

**Comment by MPreloaded** [comment]
Ok, war eine Fehler in meinem Code (Neuron muss bei mutateNode zuerst hinzugefügt werden)

**Comment by Keydara** [comment]
Okey dokey
