### ISSUE TITLE
newGeneration und evaluateGenome gemeinsam bringen enorme Fehlerquellen

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#29]
Aktuell schmeißt das Programm sehr viele Fehler, stürzt allerdings nicht ab (das sollte es besser). Versucht man nach einer Auswertung der ersten Generation eine neue zu erstellen, so funktioniert dies nicht (angeblich soll die Größe einer Liste auf -1 liegen). Anders herum schmeißt die calculateValue-Funktion eine StackOverflow Exception.

**Comment by Keydara** [comment]
Meine Vermutung bezüglich des StackOverflows ist, dass nach newGeneration() unglücklicherweise ein paar Genes einen Kreis bilden.
Sprich Neuron N1 ruft CalculateValue für N2 auf, weil N2 auf N1 zeigt. Allerdings Zeigt N1 auch auf N2, was in einer endlos Rekursion resultiert --> StackOverflow
Diese These muss ich noch Testen..

Warum Neurons.size() die Kurve kratzt erschließt sich mir noch nicht.

**Comment by Keydara** [comment]
Es scheint so zu sein, dass die Neurons Liste und/oder die Genes Liste in einem Genome nach ausführen von evaluateGenome() geleert wird.
Weil in den Methoden von newGeneration() nicht abgefangen wird, ob die Listen befüllt sind, kommt OutOfBounds für size-1 (bei Genes in matchGenomes()) und 0 bei mutateLink() für die neuron Liste...

Warum die Listen leer sind müssen wir gucken.

**Comment by Keydara** [comment]
Frage: Warum verwendet evaluateNetwork die Neuronen Liste, die von initializePool() zurückgegeben wird anstatt der Neuronen Liste die im genome gespeichert ist?

**Comment by MPreloaded** [comment]
evaluateNetwork verwendet die von initializePool, da innerhalb von der Funktion nur die Inputneuronen gesetzt und die Outputneuronen ausgelesen werden sollen... daher reicht die Liste.

Zu dem ersten... das könnte sein... da sowas eigentlich auch nicht sein soll (oder was meinst du) muss das vorher bereits abgefangen werden.

**Comment by MPreloaded** [comment]
Fehler behoben. StackOverflow entstand durch Verbindungen, die auf sich selbst zeigen. Der andere Fehler war, dass 0 keine angemessene Anzahl für eine Grenze war und die size 0 dadurch entstehen konnte, dass zwei Genomes ohne Genes gematcht wurden. Dadurch wurden keine Neuronen hinzugefügt...

MPreloaded@499c8b351b10e0a0c2f972ea12ef464af281b759
