### ISSUE TITLE
Loops innerhalb der Verbindungen

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#30]
Der bis jetzt aufgetretene Fehler wurde behoben, allerdings kann es nach deutlich mehr Generationnen (meist 5+) auch auftreten, dass Loops innerhalb der Verbindungen entstehen. 

Dies gilt es clever zu verhindern!

Eine Möglichkeit die ich sehe (die auch aus meinem Grundwissen über NE's stammt) ist die Einschränkung, dass immer nur Verbindungen zu einem höheren Level gebildet werden dürfen. Dabei würde das Output-Level den Wert INTEGER.MAX_VALUE erhalten und das Input/Bias Level den Wert 0. Das sollte auf jeden Fall auch genügend Spielraum beinhalten, um kompexe Lösungen zu ermöglichen.

**Comment by Keydara** [comment]
Es gab doch sonst auch in der Graphentheorie eine Möglichkeit, einen Graphen nach Zyklen zu durchsuchen... Vielleicht reicht das schon...

**Comment by MPreloaded** [comment]
MPreloaded@a3d3c5d0f3173b720b2949c44d4748efe71e1e62

Scheint zu funktionieren. Nach 85 Generationen (Auch wenn es ab der 70. anfängt etwas länger zu dauern) immer noch kein Fehler und keine Loop. 

Bis Problem erneut auftritt geschlossen.

**Comment by MPreloaded** [comment]
Problem doch noch nicht ganz gelöst. Problem tritt ab und zu nochmal auf... vielleicht solltest du nochmal den Code debuggen, ich scheine da gerade etwas blind für den einfachen Fehler zu sein -.-

**Comment by Keydara** [comment]
Ich bin erst Montag wieder bei meiner Debug Ausrüstung, aber werds mir dann anschauen.
Können Neuronen noch auf sich selbst zeigen?

Andere Idee: Man könnte Zyklen erlauben, aber dafür das gute alte TCP Protokoll ab kupfern :D Im speziellen denke ich an das TTL Feld, soll heißen dass Zyklen in Ordnung sind, aber nach einer bestimmten Anzahl von Übertragungen der Daten soll der Zyklus verlassen werden und die Daten direkt an die Output Neuronen gehen.
So würde man die Endlosschleife loswerden und vllt sind Zyklen noch von Vorteil, da sie eine Negative bzw positive Feedback Loop abbilden können.

**Comment by MPreloaded** [comment]
Naja, davon ausgehend, dass irgendwann durch bestimmte Anwendungen die Komplexität steigen kann, weiß ich nicht, wie es damit aussieht einfach eine feste Grenze einzuführen... Für mich läuft es immer auf Zyklenerkennung hinaus, und wenn die läuft können wir auch einfach präventiv den Zyklus verhindern, da er im Allgemeinen in NE (glaube ich) nicht vorgesehen ist.

Zu deiner Frage, nein sie können nicht auf sich selbst zeigen. Debug Code zeigt, dass es sich bei der Entstehung der Fehlermeldungen stets um 3 Neuronen handelt, die einen Zyklus bilden. Theoretisch sollte ein solcher (und jeder anderer Fall) durch die Tiefensuche abgedeckt werden, aber entweder habe ich da etwas falsch implemntiert, oder falsch durchdacht... Von daher wäre ich dir einfach sehr verbunden, wenn du es bei Zeiten mal anguckst ;)

**Comment by Keydara** [comment]
7b9ff4880419314c485f43b93aa99f9fae276315
Das Problem war, dass die Rückgabe der rekursiven Aufrufe innerhalb von checkLoopNeuron() ignoriert wurden. Die Funktion hat also brav alle Zyklen gefunden, es nur niemandem gesagt
