### ISSUE TITLE
Pfeile statt Verbindungen

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#32]
Auch in Hinsicht auf Kontrollen, ob Zyklen vorhanden sind, und um die Komplexität innerhalb der Hiddennodes betrachten zu können fände ich es cool, wenn die Verbindungen ihre Richtung anzeigen könnten :)

**Comment by Keydara** [comment]
Done
5f6d8d0f703386d148db40d156de519e5dc599ee
