### ISSUE TITLE
Anzeigen bestes Genome

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#33]
Da jetzt langsam aber sicher die ersten Bugs behoben wurden, wird es wichtig, ob der erste Test richtig abgeschlossen wird. Dafür wäre es notwendig, dass die Funktion noch angepasst wird (ist schon in Planung wie) und es möglich wäre auf Knopfdruck das global beste Netz ausgeben zu lassen (Grafisch und als log).

**Comment by Keydara** [comment]
88c5d5603382dd7531e1716d96def627c170565f
Es gibt jetzt einen Button, der das global Beste Genome selektiert

(Ist erstmal nur Prototyp-Artig, ich werde die GUI noch komplett überarbeiten)
