### ISSUE TITLE
Fitness History löschen

### ISSUE THREAD

**Issue by Keydara** [MPreloaded/NEAT#34]
Die History von Genomes, welche gelöscht werden, sollte ebenfalls gelöscht werden, damit die Map in GenomeHistory nicht unnötig anwächst.

**Comment by MPreloaded** [comment]
Wie genau meinst du das eigentlich?

**Comment by Keydara** [comment]
Genomes dienen als key. Dadurch dass ständig genomes gelöscht und neu erstellt werden, gibt es immer mehr keys in der map, aber auch mappings für genome die es gar nicht mehr gibt.

**Comment by Keydara** [comment]
Da jetzt Species betrachtet werden, erübrigt sich das Problem
