### ISSUE TITLE
Fitness Graph noch überflüssig

### ISSUE THREAD

**Issue by MPreloaded** [MPreloaded/NEAT#35]
Ich finde die Idee gut, allerdings macht es keinen Sinn von einem bestimmten Netz sich einen Verlauf anzuzeigen, da jedes Netz nur einmal simuliert wird. Dementsprechend erhält man immer einen nicht sehr aussagekräftigen Graphen. 

Möglichkeit 1: Verlauf der durchschnittlichen Fitness einer Species anzeigen.

Möglichkeit 2: Verlauf der Fitness des jeweils besten Genomes anzeigen.

Möglichkeit 3: Verlauf der durchschnittlichen Fitness der gesamten Population anzeigen (Vielleicht nicht besonders hilfreich aber vielleicht auch mal interessant zu sehen)

**Comment by Keydara** [comment]
9ab911b1fb619615ea121e7d40e55cd495ce7314
Möglichkeit 1 ist es geworden. Möglichkeit 3 wird vllt noch dazu kommen.
